# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-06 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='contenido',
            field=models.TextField(null=True, verbose_name='Contenido'),
        ),
        migrations.AddField(
            model_name='video',
            name='imagen',
            field=models.ImageField(null=True, upload_to='media/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='video',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='video.Categoria'),
        ),
    ]
